/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "background": "#fbf9f9",
        "inverse-surface": "#303031",
        "outline": "#7e7576",
        "on-background": "#1b1c1c",
        "tertiary-container": "#1a1c1c",
        "on-secondary-fixed": "#40000d",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c1c",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#93000a",
        "inverse-primary": "#c6c6c6",
        "on-error": "#ffffff",
        "secondary-container": "#e0244c",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "inverse-on-surface": "#f2f0f0",
        "on-secondary-container": "#fffbff",
        "on-tertiary-fixed": "#1a1c1c",
        "error-container": "#ffdad6",
        "secondary": "#ba0037",
        "on-primary-container": "#848484",
        "on-secondary-fixed-variant": "#920029",
        "surface-variant": "#e3e2e2",
        "primary-container": "#1b1b1b",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-bright": "#fbf9f9",
        "on-primary-fixed-variant": "#474747",
        "tertiary-fixed": "#e2e2e2",
        "surface-dim": "#dbdad9",
        "secondary-fixed": "#ffdadb",
        "primary": "#000000",
        "on-surface-variant": "#4c4546",
        "primary-fixed-dim": "#c6c6c6",
        "outline-variant": "#cfc4c5",
        "on-secondary": "#ffffff",
        "surface": "#fbf9f9",
        "secondary-fixed-dim": "#ffb2b7",
        "surface-container-highest": "#e3e2e2",
        "surface-container": "#efeded",
        "on-tertiary-container": "#838484",
        "surface-container-high": "#e9e8e7",
        "surface-container-low": "#f5f3f3",
        "surface-tint": "#5e5e5e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "120px",
        "gutter": "24px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "display-xl": ["Space Grotesk"],
        "label-bold": ["Space Grotesk"],
        "space-grotesk": ["Space Grotesk"],
      },
      keyframes: {
        'slide-in': {
          '0%': { opacity: '0', transform: 'translateX(100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'slide-in': 'slide-in 0.25s ease-out',
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "1.0", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
